In [11]:
from bs4 import BeautifulSoup 
import csv 
import pandas as pd

In [20]:
names=[]
prices=[]
changes=[]
percentChanges=[]
marketCaps=[]
totalVolumes=[]
circulatingSupplys=[]
 
for i in range(0,10):
  CryptoCurrenciesUrl = "https://in.finance.yahoo.com/cryptocurrencies?offset="+str(i)+"&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;count=50"
  r= requests.get(CryptoCurrenciesUrl)
  data=r.text
  soup=BeautifulSoup(data)
 
  for listing in soup.find_all('tr', attrs={'class':'SimpleDataTableRow'}):
    for name in listing.find_all('td', attrs={'aria-label':'Name'}):
      names.append(name.text)
    for price in listing.find_all('td', attrs={'aria-label':'Price (intraday)'}):
      prices.append(price.find('span').text)
    for change in listing.find_all('td', attrs={'aria-label':'Change'}):
      changes.append(change.text)
    for percentChange in listing.find_all('td', attrs={'aria-label':'% change'}):
      percentChanges.append(percentChange.text)
    for marketCap in listing.find_all('td', attrs={'aria-label':'Market cap'}):
      marketCaps.append(marketCap.text)
    for totalVolume in listing.find_all('td', attrs={'aria-label':'Total volume all currencies (24 hrs)'}):
      totalVolumes.append(totalVolume.text)
    for circulatingSupply in listing.find_all('td', attrs={'aria-label':'Circulating supply'}):
      circulatingSupplys.append(circulatingSupply.text)

In [21]:
names=[]
prices=[]
changes=[]
percentChanges=[]
marketCaps=[]
totalVolumes=[]
circulatingSupplys=[]
 
CryptoCurrenciesUrl = "https://in.finance.yahoo.com/currencies"
r= requests.get(CryptoCurrenciesUrl)
data=r.text
soup=BeautifulSoup(data)
 
counter = 40
for i in range(40, 404, 14):
   for listing in soup.find_all('tr', attrs={'data-reactid':i}):
      for name in listing.find_all('td', attrs={'data-reactid':i+3}):
         names.append(name.text)
      for price in listing.find_all('td', attrs={'data-reactid':i+4}):
         prices.append(price.text)
      for change in listing.find_all('td', attrs={'data-reactid':i+5}):
         changes.append(change.text)
      for percentChange in listing.find_all('td', attrs={'data-reactid':i+7}):
         percentChanges.append(percentChange.text)
pd.DataFrame({"Names": names, "Prices": prices, "Change": changes, "% Change": percentChanges})

      Names       Prices     Change  % Change
0   USD/INR      73.6650    -0.2350  -0.3180%
1   EUR/INR      82.7009    -0.3450    -0.42%
2   GBP/INR      95.4175    -0.3352    -0.35%
3   AED/INR      20.0160    -0.0580    -0.29%
4   INR/JPY       1.4349    +0.0017    +0.12%
5   SGD/INR      53.2090    -0.1690    -0.32%
6   USD/IDR  14,285.0000  +121.0000    +0.85%
7   USD/THB      31.5980    +0.0080    +0.03%
8   USD/MYR       4.1860    +0.0260    +0.63%
9   USD/ZAR      15.6745    +0.0789    +0.51%
10  USD/RUB      67.6350    +0.0850    +0.13%
11  AUD/USD       0.6604    -0.0011    -0.17%
12  AUD/JPY      69.9380    -0.2730    -0.39%
13  NZD/USD       0.6317    +0.0012    +0.18%
14  EUR/USD       1.1230    -0.0006    -0.06%
15  EUR/CAD       1.5049    -0.0002    -0.01%
16  USD/JPY     105.9140    -0.2500    -0.24%
17  GBP/USD       1.2954    -0.0001    -0.00%
18  USD/CHF       0.9451    -0.0004    -0.04%
19  USD/CAD       1.3399    -0.0002    -0.02%
20  EUR/JPY     118.9130    -0.3100    -0.26%
21  GBP/JPY     137.1910    -0.2620    -0.19%
22  EUR/GBP       0.8667    -0.0001    -0.01%
23  EUR/SEK      10.6117    +0.0161    +0.15%
24  EUR/CHF       1.0611    -0.0009    -0.09%
25  EUR/HUF     336.6200    +0.6200    +0.18%

In [22]:
prices=[]
names=[]
changes=[]
percentChanges=[]
marketCaps=[]
totalVolumes=[]
circulatingSupplys=[]
 
CryptoCurrenciesUrl = "https://in.finance.yahoo.com/world-indices"
r= requests.get(CryptoCurrenciesUrl)
data=r.text
soup=BeautifulSoup(data)
 
counter = 40
for i in range(40, 404, 14):
   for row in soup.find_all('tbody'):
      for srow in row.find_all('tr'):
         for name in srow.find_all('td', attrs={'class':'data-col1'}):
            names.append(name.text)
         for price in srow.find_all('td', attrs={'class':'data-col2'}):
            prices.append(price.text)
         for change in srow.find_all('td', attrs={'class':'data-col3'}):
            changes.append(change.text)
         for percentChange in srow.find_all('td', attrs={'class':'data-col4'}):
            percentChanges.append(percentChange.text)
 
pd.DataFrame({"Names": names, "Prices": prices, "Change": changes, "% Change": percentChanges})

                         Names     Prices     Change % Change
0                   BSE SENSEX  37,303.63  -1,166.98   -3.03%
1                     Nifty 50  10,907.00    -362.00   -3.21%
2                          Dow  26,121.28    -969.58   -3.58%
3                       Nasdaq   8,738.59    -279.49   -3.10%
4                       Nikkei  20,730.30    -598.82   -2.81%
..                         ...        ...        ...      ...
905                     MERVAL  38,390.84    +233.89   +0.61%
906                     TA-125   1,479.93     -28.91   -1.92%
907  EGX 30 Price Return Index  12,347.60    +165.10   +1.36%
908   Top 40 USD Net TRI Index   3,293.37     -45.61   -1.37%
909     S&P/NZX 50 INDEX GROSS  11,425.90    -214.99   -1.85%

[910 rows x 4 columns]

In [24]:
names=[]
prices=[]
changes=[]
percentChanges=[]
marketCaps=[]
totalVolumes=[]
circulatingSupplys=[]
 
for i in range(0,11):
    CryptoCurrenciesUrl = "https://in.finance.yahoo.com/most-active?offset="+str(i)+"&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;count=100"
    r= requests.get(CryptoCurrenciesUrl)
    data=r.text
    soup=BeautifulSoup(data)
 
    for listing in soup.find_all('tr', attrs={'class':'SimpleDataTableRow'}):
       for name in listing.find_all('td', attrs={'aria-label':'Name'}):
          names.append(name.text)
       for price in listing.find_all('td', attrs={'aria-label':'Price (intraday)'}):
          prices.append(price.find('span').text)
       for change in listing.find_all('td', attrs={'aria-label':'Change'}):
          changes.append(change.text)
       for percentChange in listing.find_all('td', attrs={'aria-label':'% change'}):
          percentChanges.append(percentChange.text)
       for marketCap in listing.find_all('td', attrs={'aria-label':'Market cap'}):
          marketCaps.append(marketCap.text)
       for totalVolume in listing.find_all('td', attrs={'aria-label':'Avg vol (3-month)'}):
          totalVolumes.append(totalVolume.text)
       for circulatingSupply in listing.find_all('td', attrs={'aria-label':'Volume'}):
          circulatingSupplys.append(circulatingSupply.text)
 
pd.DataFrame({"Names": names, "Prices": prices, "Change": changes, "% Change": percentChanges, "Market Cap": marketCaps, "Average Volume": totalVolumes,"Volume":circulatingSupplys})

Empty DataFrame
Columns: [Names, Prices, Change, % Change, Market Cap, Average Volume, Volume]
Index: []